import { CARD_CLASS, CardType } from '@/types/card.type'

const cards: CardType[] = [
	{
		id: 0,
		data: {
			id: '264',
			name: 'flash gordon',
			powerstats: {
				intelligence: 'null',
				strength: '69',
				speed: 'null',
				durability: 'null',
				power: 'null',
				combat: 'null',
			},
			biography: {
				'full-name': 'steven gordon',
				'alter-egos': 'no alter egos found.',
				aliases: ['-'],
				'place-of-birth': '-',
				'first-appearance': 'flash gordon #1 (september 1966)',
				publisher: 'null',
				alignment: 'good',
			},
			appearance: {
				gender: 'male',
				race: 'null',
				height: ['-', '0 cm'],
				weight: ['- lb', '0 kg'],
				'eye-color': '-',
				'hair-color': '-',
			},
			work: { occupation: '-', base: '-' },
			connections: { 'group-affiliation': '-', relatives: '-' },
			image: {
				url: 'https://www.superherodb.com/pictures2/portraits/10/100/1345.jpg',
			},
		},
		class: CARD_CLASS.CHARGE,
		health: 100,
		attack: 4,
		attackPerTurn: 4,
		isAttack: false,
		isDeck: true,
		mana: 4,
	},
	{
		id: 0,
		data: {
			id: '264',
			name: 'flash gordon',
			powerstats: {
				intelligence: 'null',
				strength: '69',
				speed: 'null',
				durability: 'null',
				power: 'null',
				combat: 'null',
			},
			biography: {
				'full-name': 'steven gordon',
				'alter-egos': 'no alter egos found.',
				aliases: ['-'],
				'place-of-birth': '-',
				'first-appearance': 'flash gordon #1 (september 1966)',
				publisher: 'null',
				alignment: 'good',
			},
			appearance: {
				gender: 'male',
				race: 'null',
				height: ['-', '0 cm'],
				weight: ['- lb', '0 kg'],
				'eye-color': '-',
				'hair-color': '-',
			},
			work: { occupation: '-', base: '-' },
			connections: { 'group-affiliation': '-', relatives: '-' },
			image: {
				url: 'https://www.superherodb.com/pictures2/portraits/10/100/1345.jpg',
			},
		},
		class: CARD_CLASS.CHARGE,
		health: 100,
		attack: 4,
		attackPerTurn: 4,
		isAttack: false,
		isDeck: true,
		mana: 4,
	},
	{
		id: 0,
		data: {
			id: '264',
			name: 'flash gordon',
			powerstats: {
				intelligence: 'null',
				strength: '69',
				speed: 'null',
				durability: 'null',
				power: 'null',
				combat: 'null',
			},
			biography: {
				'full-name': 'steven gordon',
				'alter-egos': 'no alter egos found.',
				aliases: ['-'],
				'place-of-birth': '-',
				'first-appearance': 'flash gordon #1 (september 1966)',
				publisher: 'null',
				alignment: 'good',
			},
			appearance: {
				gender: 'male',
				race: 'null',
				height: ['-', '0 cm'],
				weight: ['- lb', '0 kg'],
				'eye-color': '-',
				'hair-color': '-',
			},
			work: { occupation: '-', base: '-' },
			connections: { 'group-affiliation': '-', relatives: '-' },
			image: {
				url: 'https://www.superherodb.com/pictures2/portraits/10/100/1345.jpg',
			},
		},
		class: CARD_CLASS.CHARGE,
		health: 100,
		attack: 4,
		attackPerTurn: 4,
		isAttack: false,
		isDeck: true,
		mana: 4,
	},
	{
		id: 0,
		data: {
			id: '264',
			name: 'flash gordon',
			powerstats: {
				intelligence: 'null',
				strength: '69',
				speed: 'null',
				durability: 'null',
				power: 'null',
				combat: 'null',
			},
			biography: {
				'full-name': 'steven gordon',
				'alter-egos': 'no alter egos found.',
				aliases: ['-'],
				'place-of-birth': '-',
				'first-appearance': 'flash gordon #1 (september 1966)',
				publisher: 'null',
				alignment: 'good',
			},
			appearance: {
				gender: 'male',
				race: 'null',
				height: ['-', '0 cm'],
				weight: ['- lb', '0 kg'],
				'eye-color': '-',
				'hair-color': '-',
			},
			work: { occupation: '-', base: '-' },
			connections: { 'group-affiliation': '-', relatives: '-' },
			image: {
				url: 'https://www.superherodb.com/pictures2/portraits/10/100/1345.jpg',
			},
		},
		class: CARD_CLASS.CHARGE,
		health: 100,
		attack: 4,
		attackPerTurn: 4,
		isAttack: false,
		isDeck: true,
		mana: 4,
	},
	{
		id: 0,
		data: {
			id: '264',
			name: 'flash gordon',
			powerstats: {
				intelligence: 'null',
				strength: '69',
				speed: 'null',
				durability: 'null',
				power: 'null',
				combat: 'null',
			},
			biography: {
				'full-name': 'steven gordon',
				'alter-egos': 'no alter egos found.',
				aliases: ['-'],
				'place-of-birth': '-',
				'first-appearance': 'flash gordon #1 (september 1966)',
				publisher: 'null',
				alignment: 'good',
			},
			appearance: {
				gender: 'male',
				race: 'null',
				height: ['-', '0 cm'],
				weight: ['- lb', '0 kg'],
				'eye-color': '-',
				'hair-color': '-',
			},
			work: { occupation: '-', base: '-' },
			connections: { 'group-affiliation': '-', relatives: '-' },
			image: {
				url: 'https://www.superherodb.com/pictures2/portraits/10/100/1345.jpg',
			},
		},
		class: CARD_CLASS.CHARGE,
		health: 100,
		attack: 4,
		attackPerTurn: 4,
		isAttack: false,
		isDeck: true,
		mana: 4,
	},
	{
		id: 0,
		data: {
			id: '264',
			name: 'flash gordon',
			powerstats: {
				intelligence: 'null',
				strength: '69',
				speed: 'null',
				durability: 'null',
				power: 'null',
				combat: 'null',
			},
			biography: {
				'full-name': 'steven gordon',
				'alter-egos': 'no alter egos found.',
				aliases: ['-'],
				'place-of-birth': '-',
				'first-appearance': 'flash gordon #1 (september 1966)',
				publisher: 'null',
				alignment: 'good',
			},
			appearance: {
				gender: 'male',
				race: 'null',
				height: ['-', '0 cm'],
				weight: ['- lb', '0 kg'],
				'eye-color': '-',
				'hair-color': '-',
			},
			work: { occupation: '-', base: '-' },
			connections: { 'group-affiliation': '-', relatives: '-' },
			image: {
				url: 'https://www.superherodb.com/pictures2/portraits/10/100/1345.jpg',
			},
		},
		class: CARD_CLASS.CHARGE,
		health: 100,
		attack: 4,
		attackPerTurn: 4,
		isAttack: false,
		isDeck: true,
		mana: 4,
	},
]

export default cards
